'use strict';
const {connectInMemoryMongo,disconnectInMemoryMongo,clearDatabase}=require('./helpers/testServer');
const controller=require('../src/controllers/retentionAdmin.controller');
const User=require('../src/models/user.model');const Institution=require('../src/models/Institution');
const Wallet=require('../src/models/InstitutionCreditWallet');const PersonalWallet=require('../src/models/CreditWallet');const Audit=require('../src/models/AdminAuditLog');
const response=()=>({statusCode:200,body:null,status(code){this.statusCode=code;return this},json(body){this.body=body;return this}});
describe('negotiated institution credit grants',()=>{let admin,teacher,institution;
 beforeAll(connectInMemoryMongo);afterAll(disconnectInMemoryMongo);beforeEach(async()=>{await clearDatabase();admin=await User.create({firebaseUid:'topup-admin',email:'admin@example.test',role:'admin'});teacher=await User.create({firebaseUid:'topup-teacher',email:'teacher@example.test',role:'teacher'});institution=await Institution.create({name:'School',ownerUserId:teacher._id,status:'ACTIVE'});await Wallet.create({institutionId:institution._id,monthlyCredits:10,monthlyCreditsUsed:4,cycleStart:new Date('2026-09-01'),cycleEnd:new Date('2026-10-01')});await PersonalWallet.create({userId:teacher._id,monthlyCredits:5,monthlyCreditsUsed:1,purchasedCredits:7,bonusCredits:2,lastCreditReset:new Date('2026-09-01'),billingCycleStart:new Date('2026-09-01'),billingCycleEnd:new Date('2026-10-01')});});
 async function grant(body){const res=response();await controller.addInstitutionCredits({params:{id:String(institution._id)},body,user:admin},res);return res;}
 test('adds the shared balance once and records the complete admin audit without touching personal credits',async()=>{const body={amount:25,reason:'Contract PO-42',note:'September add-on',idempotencyKey:'grant-request-123'};const [first,second]=await Promise.all([grant(body),grant(body)]);expect(first.statusCode).toBe(200);expect(second.statusCode).toBe(200);const wallet=await Wallet.findOne({institutionId:institution._id});expect(wallet.topUpCredits).toBe(25);const personal=await PersonalWallet.findOne({userId:teacher._id});expect(personal).toMatchObject({monthlyCredits:5,monthlyCreditsUsed:1,purchasedCredits:7,bonusCredits:2});const audit=await Audit.findOne({action:'INSTITUTION_CREDITS_ADDED'});expect(audit).toMatchObject({adminUserId:admin._id,targetId:String(institution._id),amount:25,operationType:'INSTITUTION_POOL_TOP_UP',previousBalance:6,newBalance:31,reason:'Contract PO-42',status:'COMPLETED'});expect(await Audit.countDocuments({action:'INSTITUTION_CREDITS_ADDED'})).toBe(1);});
 test('rejects invalid amounts and missing reasons before mutation',async()=>{expect((await grant({amount:0,reason:'x',idempotencyKey:'invalid-1'})).statusCode).toBe(400);expect((await grant({amount:2,reason:'',idempotencyKey:'invalid-2'})).statusCode).toBe(400);const wallet=await Wallet.findOne({institutionId:institution._id});expect(wallet.topUpCredits).toBe(0);});
});
