'use strict';
const {connectInMemoryMongo,disconnectInMemoryMongo,clearDatabase}=require('./helpers/testServer');const Plan=require('../src/models/Plan');const Pack=require('../src/models/CreditPack');const controller=require('../src/controllers/pricingAdmin.controller');
const pricingRealtime=require('../src/services/pricingRealtime.service');
const response=()=>({statusCode:200,body:null,status(code){this.statusCode=code;return this},json(body){this.body=body;return this}});async function call(handler,{params={},body={}}={}){const res=response();await handler({params,body},res);return res}
const valid={name:'Essential Annual',monthlyCredits:300,monthlyPrice:99,annualPrice:null,active:true,displayOrder:1,recommended:false,softThresholdPercent:50,warningThresholdPercent:80,stripeProductId:'',stripeMonthlyPriceId:'',stripeAnnualPriceId:''};
describe('admin pricing legacy compatibility',()=>{beforeAll(connectInMemoryMongo);afterAll(disconnectInMemoryMongo);beforeEach(clearDatabase);
 test('GET maps sparse raw legacy plans and packs to complete DTOs',async()=>{await Plan.collection.insertOne({name:'Legacy',slug:'legacy_plan',price:4,currency:'USD',isActive:true});await Pack.collection.insertOne({name:'Ten',code:'CREDITS_10',credits:10,price:1.99,currency:'USD',active:true});const res=await call(controller.getConfig);expect(res.body.plans[0]).toMatchObject({monthlyPrice:4,annualPrice:null,monthlyCredits:0,displayOrder:0,recommended:false,assessmentCreditNudges:{softThresholdPercent:50,warningThresholdPercent:80},stripe:{productId:'',monthlyPriceId:'',annualPriceId:''},kind:'legacy'});expect(res.body.packs[0]).toMatchObject({code:'CREDITS_10',allowedPlans:[],displayOrder:0,stripePriceId:''});});
 test('GET exposes only safe provider capability metadata',async()=>{const previous=process.env.PAYMENT_PROVIDER;process.env.PAYMENT_PROVIDER='paypal';process.env.PAYPAL_CLIENT_SECRET='never-return-this';const res=await call(controller.getConfig);expect(res.body.provider).toEqual({activePaymentProvider:'paypal',paypalEnabled:true,stripeEnabled:expect.any(Boolean)});expect(JSON.stringify(res.body)).not.toContain('never-return-this');delete process.env.PAYPAL_CLIENT_SECRET;if(previous===undefined)delete process.env.PAYMENT_PROVIDER;else process.env.PAYMENT_PROVIDER=previous});
 test('valid annual and free edits save flat typed contracts and backfill missing nested objects',async()=>{await Plan.collection.insertOne({name:'Essential Annual',slug:'essential_annual',price:99,isActive:true});let res=await call(controller.updatePlan,{params:{slug:'essential_annual'},body:valid});expect(res.statusCode).toBe(200);let saved=await Plan.findOne({slug:'essential_annual'}).lean();expect(saved.features.essayAnalysesPerMonth).toBe(300);expect(saved.assessmentCreditNudges).toMatchObject({softThresholdPercent:50,warningThresholdPercent:80});expect(res.body.plan.stripe).toEqual({productId:'',monthlyPriceId:'',annualPriceId:''});await Plan.collection.insertOne({name:'Free',slug:'free',price:0});res=await call(controller.updatePlan,{params:{slug:'free'},body:{...valid,name:'Free',monthlyCredits:25,monthlyPrice:0,annualPrice:null}});expect(res.statusCode).toBe(200);});
 test.each([
  [{...valid,softThresholdPercent:80,warningThresholdPercent:80},'Soft threshold must be lower than warning threshold.'],
  [Object.fromEntries(Object.entries(valid).filter(([key])=>key!=='displayOrder')),'Display order must be a non-negative integer.'],
  [{...valid,monthlyCredits:'300'},'Monthly Assessment Credits must be a non-negative integer.'],
  [{...valid,monthlyPrice:'99'},'Monthly price must be zero or greater.']
 ])('rejects invalid field contracts with a specific message',async(body,message)=>{await Plan.create({name:'Essential Annual',slug:'essential_annual',price:99});const res=await call(controller.updatePlan,{params:{slug:'essential_annual'},body});expect(res.statusCode).toBe(400);expect(res.body.message).toBe(message);});
 test('optional Stripe IDs may stay blank or update without affecting other values',async()=>{await Plan.create({name:'Essential Annual',slug:'essential_annual',price:99,stripe:{productId:'old'}});expect((await call(controller.updatePlan,{params:{slug:'essential_annual'},body:{...valid,stripeProductId:'prod_new'}})).statusCode).toBe(200);const plan=await Plan.findOne({slug:'essential_annual'});expect(plan.stripe.productId).toBe('prod_new');expect(plan.stripe.monthlyPriceId).toBeUndefined();});
 test('emits only after successful plan and pack persistence and tolerates emitter failure',async()=>{const publish=jest.spyOn(pricingRealtime,'publishPricingConfigUpdated');await Plan.create({name:'Essential Annual',slug:'essential_annual',price:99});expect((await call(controller.updatePlan,{params:{slug:'essential_annual'},body:valid})).statusCode).toBe(200);expect(publish).toHaveBeenLastCalledWith({entity:'plan',key:'essential_annual'});publish.mockClear();expect((await call(controller.updatePlan,{params:{slug:'essential_annual'},body:{...valid,displayOrder:-1}})).statusCode).toBe(400);expect(publish).not.toHaveBeenCalled();await Pack.create({name:'Ten',code:'CREDITS_10',credits:10,price:1.99,currency:'USD',active:true,allowedPlans:['essential_annual']});expect((await call(controller.updatePack,{params:{code:'CREDITS_10'},body:{name:'Ten',credits:10,price:1.99,currency:'USD',active:true,allowedPlans:['essential_annual'],displayOrder:1,stripePriceId:''}})).statusCode).toBe(200);expect(publish).toHaveBeenLastCalledWith({entity:'credit_pack',key:'CREDITS_10'});publish.mockImplementation(()=>{throw new Error('stream failure')});expect((await call(controller.updatePlan,{params:{slug:'essential_annual'},body:valid})).statusCode).toBe(200);publish.mockRestore()});
});
