'use strict';
process.env.NODE_ENV='test';
const {connectInMemoryMongo,disconnectInMemoryMongo,clearDatabase}=require('./helpers/testServer');
const controller=require('../src/controllers/retentionAdmin.controller');const User=require('../src/models/user.model');
const Referral=require('../src/models/Referral');const Reward=require('../src/models/BonusRewardGrant');const Milestone=require('../src/models/ProfessionalMilestone');
const Institution=require('../src/models/Institution');const Wallet=require('../src/models/InstitutionCreditWallet');
function response(){return{statusCode:200,body:null,status(code){this.statusCode=code;return this},json(body){this.body=body;return this}}}
async function call(handler,query={}){const res=response();await handler({query},res);return res.body.data}
describe('retention admin operational search',()=>{let alice,bob;
 beforeAll(connectInMemoryMongo);afterAll(disconnectInMemoryMongo);beforeEach(async()=>{await clearDatabase();alice=await User.create({firebaseUid:'ops-a',email:'alice@example.test',displayName:'Alice Teacher',role:'teacher'});bob=await User.create({firebaseUid:'ops-b',email:'bob@example.test',displayName:'Bob Teacher',role:'teacher'});});
 test('filters referral users and keeps pagination total consistent',async()=>{await Referral.create({referrerUserId:alice._id,referredUserId:bob._id,codeUsed:'ONE'});const other=await User.create({firebaseUid:'ops-c',email:'charlie@example.test',role:'teacher'});const fourth=await User.create({firebaseUid:'ops-d',email:'dana@example.test',role:'teacher'});await Referral.create({referrerUserId:other._id,referredUserId:fourth._id,codeUsed:'TWO'});const result=await call(controller.referrals,{search:'Alice',page:1,limit:1});expect(result.total).toBe(1);expect(result.items).toHaveLength(1);expect(result.items[0].referrerUserId.email).toBe('alice@example.test');});
 test('searches reward event type and milestone title/key',async()=>{await Reward.create({userId:alice._id,eventType:'FIRST_ASSESSMENT',eventKey:'a',amount:5,repeatPolicy:'ONCE',idempotencyKey:'reward-a'});await Reward.create({userId:bob._id,eventType:'FIRST_CLASS',eventKey:'b',amount:5,repeatPolicy:'ONCE',idempotencyKey:'reward-b'});expect((await call(controller.rewards,{search:'ASSESSMENT'})).total).toBe(1);await Milestone.create({userId:alice._id,milestoneKey:'ASSESSMENTS_10',metricType:'ASSESSMENTS_COMPLETED',threshold:10,sourceValue:10});const byKey=await call(controller.milestones,{search:'ASSESSMENTS_10'});expect(byKey.total).toBe(1);});
 test('escapes regex-special search and empty search preserves all institutions',async()=>{const start=new Date('2026-08-01T00:00:00Z'),end=new Date('2026-09-01T00:00:00Z');for(const [name,owner]of [['School [One]',alice],['School Two',bob]]){const institution=await Institution.create({name,ownerUserId:owner._id,seatLimit:2});await Wallet.create({institutionId:institution._id,monthlyCredits:10,cycleStart:start,cycleEnd:end});}const literal=await call(controller.institutions,{search:'[One]',page:1,limit:25});expect(literal.total).toBe(1);expect(literal.items[0].name).toBe('School [One]');expect((await call(controller.institutions,{search:'',page:1,limit:25})).total).toBe(2);});
});
