const { buildSubmissionFeedbackReportViewModel, esc } = require('../src/pdf/sample/submissionFeedbackReportViewModel');
const { renderSubmissionFeedbackReportHtml } = require('../src/pdf/submissionFeedbackReportTemplate');

function fixture() { const text='Page one text.\n\nPage two text.'; return { generatedAt:'x', identity:{}, legend:[{symbol:'AGR',label:'Agreement',category:'GRAMMAR'}],
  submission:{_id:'s',files:['a','b'],canonicalText:text,correctionStatus:'completed',correctionSourceHash:'h',imageDataByFileId:{a:'data:a',b:null},
    transcriptPages:[{fileId:'b',pageNumber:1,startChar:16,endChar:30,text:'Page two text.'},{fileId:'a',pageNumber:1,startChar:0,endChar:14,text:'Page one text.'}],
    writingCorrections:[{id:'c1',fileId:'a',page:1,category:'GRAMMAR',symbol:'AGR',color:'#0a0',quotedText:'Page',message:'m',suggestedText:'s',startChar:0,endChar:4,bboxList:[{x:1,y:1,w:2,h:2},{x:4,y:1,w:2,h:2}]},{id:'c2',fileId:'b',page:1,category:'GRAMMAR',symbol:'AGR',color:'#0a0',quotedText:'two',message:'m',suggestedText:'s',startChar:21,endChar:24,bboxList:[{x:1,y:1,w:2,h:2}]}]},
  evaluation:{status:'completed',evaluationSourceHash:'h',assessmentVersion:'writing-rubric-100-v2',evaluationVersion:'canonical-evaluation-2',overallScore:90,grade:'A',rubricScores:{GRAMMAR:{score:20,maxScore:25,comment:'x'}}},
  feedback:{overriddenByTeacher:false,detailedFeedbackSourceHash:'h',detailedFeedback:{areasForImprovement:[],strengths:[],actionSteps:[]}} }; }

describe('sample submission report view model',()=>{
  test('orders every page once and filters corrections by file and page',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages.map(p=>p.fileId)).toEqual(['a','b']); expect(vm.submittedPages[0].corrections.map(c=>c.id)).toEqual(['c1']); expect(vm.submittedPages[1].corrections.map(c=>c.id)).toEqual(['c2']);});
  test('keeps one display number per correction and all verified boxes',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages[0].corrections[0].displayNumber).toBe(1); expect(vm.submittedPages[0].corrections[0].bboxList).toHaveLength(2); expect(vm.submittedPages[1].corrections[0].displayNumber).toBe(2);});
  test('highlights later page ranges and suppresses stale evaluation',()=>{const data=fixture(); let vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[1].transcript.highlightedSegments.some(s=>s.correctionNumbers.includes(2))).toBe(true); data.evaluation.evaluationSourceHash='old'; vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.result.overallScore).toBeNull(); expect(vm.categoryScores).toEqual([]);});
  test('escapes untrusted document content and tolerates missing image/comments',()=>{const data=fixture(); data.identity.title='<script>alert(1)</script>'; data.feedback.teacherComments=''; const vm=buildSubmissionFeedbackReportViewModel(data); expect(esc(data.identity.title)).toBe('&lt;script&gt;alert(1)&lt;/script&gt;'); expect(vm.submittedPages[1].imageDataUrl).toBeNull();});
  test('supports ten pages through the same loop',()=>{const data=fixture(); data.submission.files=Array.from({length:10},(_,i)=>`f${i}`); data.submission.transcriptPages=data.submission.files.map((fileId,i)=>({fileId,pageNumber:1,startChar:0,endChar:1,text:'x'})); data.submission.writingCorrections=[]; expect(buildSubmissionFeedbackReportViewModel(data).submittedPages).toHaveLength(10);});
  test('rejects invalid and duplicate boxes but keeps one marker/callout identity',()=>{const data=fixture(); data.submission.writingCorrections[0].bboxList.push({x:1,y:1,w:2,h:2},{x:NaN,y:1,w:2,h:2},{x:1,y:1,w:0,h:2}); const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[0].corrections[0].bboxList).toHaveLength(2); expect(vm.submittedPages[0].corrections[0].displayNumber).toBe(1);});
  test('shows exactly five statistics categories and keeps SP under mechanics',()=>{const data=fixture(); data.submission.writingCorrections.push({id:'sp',fileId:'b',page:1,category:'MECHANICS',symbol:'SP',startChar:25,endChar:29,bboxList:[]}); const vm=buildSubmissionFeedbackReportViewModel(data); expect(Object.keys(vm.statistics)).toEqual(['content','grammar','organization','vocabulary','mechanics','total']); expect(vm.statistics.mechanics).toBe(1); expect(vm.statistics.SP).toBeUndefined();});
  test('rubric issue counts use canonical statistics and bounded scores sum to overall',()=>{const data=fixture(); data.evaluation.rubricScores.GRAMMAR.issueCount=0; data.evaluation.rubricScores.CONTENT={score:30,maxScore:20,comment:'legacy'}; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.categoryScores.find(x=>x.category==='GRAMMAR').issueCount).toBe(2); expect(vm.categoryScores.find(x=>x.category==='CONTENT').score).toBe(20); expect(vm.result.overallScore).toBe(40);});
  test('suppresses stale detailed feedback and preserves teacher override',()=>{const data=fixture(); data.feedback.detailedFeedbackSourceHash='old'; let vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.detailedFeedback.status).toBe('stale'); data.feedback.overriddenByTeacher=true; vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.result.teacherAdjusted).toBe(true); expect(vm.detailedFeedback.areasForImprovement).toEqual([]);});
  test('omits empty optional sections and never emits Detected Issues',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).not.toContain('Detected Issues'); expect(html).not.toContain('No data available'); expect(html).not.toContain('AI Per-Category Feedback'); expect(html).not.toContain('Teacher comments</h3>');});
  test('renders second-file annotation and highlight with the same callout number',()=>{const data=fixture(); data.submission.imageDataByFileId.b='data:image/png;base64,AA=='; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect(html).toContain('Submitted Page 2'); expect(html).toContain('#02 AGR'); expect(html).toMatch(/Submitted Page 2[\s\S]*marker[\s\S]*#02 AGR/);});
  test('places the existing results summary after identity and before the submitted document without a forced break',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); const identity=html.indexOf('class="identity"'); const results=html.indexOf('class="results-summary"'); const scores=html.indexOf('Scores and Correction Statistics'); const submitted=html.indexOf('SUBMITTED DOCUMENT'); expect(identity).toBeLessThan(results); expect(results).toBeLessThan(scores); expect(scores).toBeLessThan(submitted); const resultTag=html.slice(results-20,results+80); expect(resultTag).not.toContain('page-break'); expect(html).toContain('.results-summary{margin-top:4mm;break-before:auto;page-break-before:auto}');});
  test('uses a compact image grid, continuous transcription, and active legend only',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); const p1=html.indexOf('Submitted Page 1'); const p2=html.indexOf('Submitted Page 2'); const transcript=html.indexOf('Transcribed Essay'); const feedback=html.indexOf('Detailed Feedback'); expect(p1).toBeGreaterThan(-1); expect(p1).toBeLessThan(p2); expect(p2).toBeLessThan(transcript); expect(transcript).toBeLessThan(feedback); expect(html).toContain('class="image-grid"'); expect(html).not.toContain('Complete correction legend');});
  test('image markers include one canonical reference and official symbol per correction',()=>{const data=fixture(); data.submission.imageDataByFileId.b='data:image/png;base64,AA=='; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect((html.match(/class="marker"/g)||[])).toHaveLength(2); expect(html).toContain('#01 AGR'); expect(html).toContain('#02 AGR'); expect(html).not.toContain('#01 AG<');});
  test('missing second image preserves its transcript and corrections',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages[1].imageDataUrl).toBeNull(); const html=renderSubmissionFeedbackReportHtml(vm); expect(html).toContain('Submitted image unavailable'); expect(html).toMatch(/Page\s+<mark[^>]*>two/);});
  test('escapes all dynamic report text',()=>{const data=fixture(); data.identity={title:'<style>bad</style>',studentName:'<img src=x onerror=alert(1)>'}; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect(html).not.toContain('<style>bad</style>'); expect(html).not.toContain('<img src=x'); expect(esc('<script>')).toBe('&lt;script&gt;');});
  test('production report code has no provider calls, database writes, or page-only filtering',()=>{const fs=require('fs'); const files=['../src/services/submissionFeedbackReport.service.js','../src/modules/submissionFeedbackPdfGenerator.js','../src/pdf/submissionFeedbackReportTemplate.js'].map(p=>fs.readFileSync(require('path').join(__dirname,p),'utf8')).join('\n'); expect(files).not.toMatch(/LanguageTool|Google Vision|semantic AI|updateOne|findOneAndUpdate|\.save\(/i); expect(files).not.toMatch(/filter\s*\(.*Number\(c\.page\).*pageNum/);});
});
