'use strict';
const fs=require('fs'); const os=require('os'); const path=require('path');
const { safeFilePath, resolvePersistedPageAssets, buildPersistedSubmissionFeedbackReport }=require('../src/services/submissionFeedbackReport.service');
const { PDFDocument }=require('pdf-lib');

describe('submission feedback production hardening',()=>{
  let root;
  beforeEach(()=>{root=fs.mkdtempSync(path.join(os.tmpdir(),'pdf-assets-')); process.env.UPLOAD_BASE_PATH=root;});
  afterEach(()=>{fs.rmSync(root,{recursive:true,force:true}); delete process.env.UPLOAD_BASE_PATH;});
  test('accepts a real file inside uploads root and rejects traversal',()=>{const valid=path.join(root,'page.png'); fs.writeFileSync(valid,'x'); expect(safeFilePath({path:valid})).toBe(fs.realpathSync(valid)); expect(safeFilePath({path:path.join(root,'..','secret.png')})).toBeNull();});
  test('rejects a symbolic-link escape when supported',()=>{const outside=path.join(os.tmpdir(),`outside-${Date.now()}.png`); fs.writeFileSync(outside,'x'); const link=path.join(root,'link.png'); try{fs.symlinkSync(outside,link); expect(safeFilePath({path:link})).toBeNull();}catch{/* Windows may deny symlink creation */}finally{fs.rmSync(outside,{force:true});}});
  test('production endpoint keeps authorization, validation, private headers, and fixed filename',()=>{const route=fs.readFileSync(path.join(__dirname,'../src/routes/pdf.routes.js'),'utf8'); const controller=fs.readFileSync(path.join(__dirname,'../src/controllers/pdf.controller.js'),'utf8'); expect(route).toMatch(/verifyJwtToken[\s\S]*requireRole\(\['student', 'teacher'\]\)[\s\S]*isMongoId/); expect(controller).toContain('assertTeacherOwnsClassOrThrow'); expect(controller).toContain('private, no-cache, no-store'); expect(controller).toContain('X-Content-Type-Options'); expect(controller).toContain('submission-feedback.pdf');});
  test('render path remains read-only and provider-free',()=>{const files=['../src/controllers/pdf.controller.js','../src/services/submissionFeedbackReport.service.js','../src/modules/submissionFeedbackPdfGenerator.js'].map((name)=>fs.readFileSync(path.join(__dirname,name),'utf8')).join('\n'); expect(files).not.toMatch(/buildOcrCorrections|LanguageTool|semanticWriting|canonicalEvaluation|updateOne|findOneAndUpdate|\.save\(/);});
  test('browser network policy permits inline resources but blocks remote requests',()=>{const source=fs.readFileSync(path.join(__dirname,'../src/modules/submissionFeedbackPdfGenerator.js'),'utf8'); expect(source).toMatch(/startsWith\('data:'\)/); expect(source).toMatch(/startsWith\('blob:'\)/); expect(source).toMatch(/else request\.abort\(\)/);});
  test('processing states return controlled conflicts without provider work',async()=>{const base={_id:'s',files:['f'],ocrPages:[],ocrStatus:'processing',writingCorrections:[],correctionStatus:'processing'};await expect(buildPersistedSubmissionFeedbackReport({submission:base})).rejects.toMatchObject({statusCode:409});const withText={...base,ocrStatus:'completed',ocrPages:[{fileId:'f',pageNumber:1,text:'Persisted text.',words:[]}]};await expect(buildPersistedSubmissionFeedbackReport({submission:withText})).rejects.toMatchObject({statusCode:409});});
  test('completed zero-correction and partial persisted reports remain honest',async()=>{const submission={_id:'s',files:['f'],ocrStatus:'completed',correctionStatus:'completed',correctionSourceHash:'h',writingCorrections:[],ocrPages:[{fileId:'f',pageNumber:1,text:'Persisted text.',words:[]}]};const {viewModel}=await buildPersistedSubmissionFeedbackReport({submission,submissionFeedback:{evaluationSourceHash:'old',detailedFeedbackSourceHash:'old'}});expect(viewModel.statistics.total).toBe(0);expect(viewModel.result.overallScore).toBeNull();expect(viewModel.submittedPages[0].corrections).toEqual([]);});
  test('multi-page PDF assets are rasterized in page order without shell execution',async()=>{const document=await PDFDocument.create();document.addPage([200,300]);document.addPage([200,300]);const pdfPath=path.join(root,'two-pages.pdf');fs.writeFileSync(pdfPath,await document.save());const assets=await resolvePersistedPageAssets([{_id:'f',path:pdfPath,originalName:'two-pages.pdf'}]);expect(Object.keys(assets.byPageKey)).toEqual(['f:1','f:2']);expect(assets.byPageKey['f:2']).toMatch(/^data:image\/png;base64,/);});
});
