const { buildSubmissionFeedbackReportViewModel, esc } = require('../src/pdf/sample/submissionFeedbackReportViewModel');
const { ASSESSMENT_VERSION, EVALUATION_VERSION } = require('../src/services/rubricLanguageScoring.service');
const { renderSubmissionFeedbackReportHtml } = require('../src/pdf/submissionFeedbackReportTemplate');

function fixture() { const text='Page one text.\n\nPage two text.'; return { generatedAt:'x', identity:{}, legend:[{symbol:'AGR',label:'Agreement',category:'GRAMMAR'}],
  submission:{_id:'s',files:['a','b'],canonicalText:text,correctionStatus:'completed',correctionSourceHash:'h',imageDataByFileId:{a:'data:a',b:null},
    transcriptPages:[{fileId:'b',pageNumber:1,startChar:16,endChar:30,text:'Page two text.',imageWidth:900,imageHeight:1180},{fileId:'a',pageNumber:1,startChar:0,endChar:14,text:'Page one text.',imageWidth:900,imageHeight:1180}],
    writingCorrections:[{id:'c1',fileId:'a',page:1,category:'GRAMMAR',symbol:'AGR',color:'#0a0',quotedText:'Page',message:'m',suggestedText:'s',startChar:0,endChar:4,bboxList:[{x:1,y:1,w:2,h:2},{x:4,y:1,w:2,h:2}]},{id:'c2',fileId:'b',page:1,category:'GRAMMAR',symbol:'AGR',color:'#0a0',quotedText:'two',message:'m',suggestedText:'s',startChar:21,endChar:24,bboxList:[{x:1,y:1,w:2,h:2}]}]},
  evaluation:{status:'completed',evaluationSourceHash:'h',assessmentVersion:ASSESSMENT_VERSION,evaluationVersion:EVALUATION_VERSION,overallScore:20,grade:'A',rubricScores:{GRAMMAR:{score:20,maxScore:25,comment:'x'}}},
  feedback:{overriddenByTeacher:false,detailedFeedbackSourceHash:'h',detailedFeedback:{areasForImprovement:[],strengths:[],actionSteps:[]}} }; }

describe('sample submission report view model',()=>{
  test('uses one A4 portrait page contract for cover, evidence, and feedback',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).not.toContain('@page evidence'); expect(html).toContain('@page{size:A4'); expect(html).not.toMatch(/A4 landscape|landscape\s*:/i);});
  test('orders every page once and filters corrections by file and page',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages.map(p=>p.fileId)).toEqual(['a','b']); expect(vm.submittedPages[0].corrections.map(c=>c.id)).toEqual(['c1']); expect(vm.submittedPages[1].corrections.map(c=>c.id)).toEqual(['c2']);});
  test('keeps one display number per correction and all verified boxes',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages[0].corrections[0].displayNumber).toBe(1); expect(vm.submittedPages[0].corrections[0].bboxList).toHaveLength(2); expect(vm.submittedPages[1].corrections[0].displayNumber).toBe(2);});
  test('numbers corrections by page and bbox reading order instead of source array order',()=>{const data=fixture(); data.submission.files=['a']; data.submission.transcriptPages=[data.submission.transcriptPages.find(page=>page.fileId==='a')]; data.submission.writingCorrections=[
    {...data.submission.writingCorrections[0],id:'bottom',startChar:0,bboxList:[{x:20,y:70,w:5,h:2}]},
    {...data.submission.writingCorrections[0],id:'top-right',startChar:8,bboxList:[{x:70,y:10.4,w:5,h:2}]},
    {...data.submission.writingCorrections[0],id:'top-left',startChar:12,bboxList:[{x:10,y:10,w:5,h:2}]}
  ]; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[0].corrections.map(item=>[item.id,item.displayNumber])).toEqual([
    ['top-left',1],['top-right',2],['bottom',3]
  ]);});
  test('normalizes pixel correction boxes using the submitted image dimensions',()=>{const data=fixture(); data.submission.writingCorrections[0].bboxList=[{x:90,y:118,w:90,h:59,unit:'px'}]; const box=buildSubmissionFeedbackReportViewModel(data).submittedPages[0].corrections[0].bboxList[0]; expect(box).toEqual({x:10,y:10,w:10,h:5});});
  test('maps normalized asset width and height into submitted image dimensions',()=>{const data=fixture(); delete data.submission.transcriptPages[0].imageWidth; delete data.submission.transcriptPages[0].imageHeight; data.submission.transcriptPages[0].width=1440; data.submission.transcriptPages[0].height=1920; const vm=buildSubmissionFeedbackReportViewModel(data); const page=vm.submittedPages.find(item=>item.fileId==='b'); expect(page.imageWidth).toBe(1440); expect(page.imageHeight).toBe(1920);});
  test('highlights later page ranges and suppresses stale evaluation',()=>{const data=fixture(); let vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[1].transcript.highlightedSegments.some(s=>s.correctionNumbers.includes(2))).toBe(true); data.evaluation.evaluationSourceHash='old'; vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.result.overallScore).toBeNull(); expect(vm.categoryScores).toEqual([]);});
  test('escapes untrusted document content and tolerates missing image/comments',()=>{const data=fixture(); data.identity.title='<script>alert(1)</script>'; data.feedback.teacherComments=''; const vm=buildSubmissionFeedbackReportViewModel(data); expect(esc(data.identity.title)).toBe('&lt;script&gt;alert(1)&lt;/script&gt;'); expect(vm.submittedPages[1].imageDataUrl).toBeNull();});
  test('supports ten pages through the same loop',()=>{const data=fixture(); data.submission.files=Array.from({length:10},(_,i)=>`f${i}`); data.submission.transcriptPages=data.submission.files.map((fileId,i)=>({fileId,pageNumber:1,startChar:0,endChar:1,text:'x'})); data.submission.writingCorrections=[]; expect(buildSubmissionFeedbackReportViewModel(data).submittedPages).toHaveLength(10);});
  test('rejects invalid and duplicate boxes but keeps one marker/callout identity',()=>{const data=fixture(); data.submission.writingCorrections[0].bboxList.push({x:1,y:1,w:2,h:2},{x:NaN,y:1,w:2,h:2},{x:1,y:1,w:0,h:2}); const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[0].corrections[0].bboxList).toHaveLength(2); expect(vm.submittedPages[0].corrections[0].displayNumber).toBe(1);});
  test('shows exactly five statistics categories and keeps SP under mechanics',()=>{const data=fixture(); data.submission.writingCorrections.push({id:'sp',fileId:'b',page:1,category:'MECHANICS',symbol:'SP',startChar:25,endChar:29,bboxList:[]}); const vm=buildSubmissionFeedbackReportViewModel(data); expect(Object.keys(vm.statistics)).toEqual(['content','grammar','organization','vocabulary','mechanics','total']); expect(vm.statistics.mechanics).toBe(1); expect(vm.statistics.SP).toBeUndefined();});
  test('rubric issue counts use canonical statistics and PDF never replaces the persisted score',()=>{const data=fixture(); data.evaluation.rubricScores.GRAMMAR.issueCount=0; data.evaluation.rubricScores.CONTENT={score:30,maxScore:20,comment:'legacy'}; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.categoryScores.find(x=>x.category==='GRAMMAR').issueCount).toBe(2); expect(vm.categoryScores.find(x=>x.category==='CONTENT').score).toBe(20); expect(vm.result.overallScore).toBe(20); expect(vm.diagnostics.persistedScoreMismatch).toBe(true);});
  test.each([85.5, 0])('preserves persisted canonical overall score %s', (overallScore)=>{const data=fixture(); data.evaluation.overallScore=overallScore; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.result.overallScore).toBe(overallScore);});
  test('shows unavailable for missing or failed canonical evaluation',()=>{const missing=fixture(); delete missing.evaluation.overallScore; expect(buildSubmissionFeedbackReportViewModel(missing).result.overallScore).toBeNull(); const failed=fixture(); failed.evaluation.status='failed'; expect(buildSubmissionFeedbackReportViewModel(failed).result.overallScore).toBeNull();});
  test('suppresses stale detailed feedback and preserves teacher override',()=>{const data=fixture(); data.feedback.detailedFeedbackSourceHash='old'; let vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.detailedFeedback.status).toBe('stale'); data.feedback.overriddenByTeacher=true; vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.result.teacherAdjusted).toBe(true); expect(vm.detailedFeedback.areasForImprovement).toEqual([]);});
  test('uses the previous PDF score label without provisional review messaging',()=>{const data=fixture(); data.evaluation.grade='F'; data.evaluation.overallScore=51; data.evaluation.rubricScores={CONTENT:{score:7,maxScore:20},ORGANIZATION:{score:9,maxScore:20},GRAMMAR:{score:14,maxScore:25},VOCABULARY:{score:11,maxScore:20},MECHANICS:{score:5.5,maxScore:10},PRESENTATION:{score:4.5,maxScore:5}}; const vm=buildSubmissionFeedbackReportViewModel(data); const html=renderSubmissionFeedbackReportHtml(vm); expect(vm.result).toMatchObject({overallScore:51,grade:'F'}); expect(html).toContain('OVERALL RESULT'); expect(html).toContain('Grade F'); expect(html).not.toContain('PROVISIONAL SCORE'); expect(html).not.toContain('Awaiting teacher review'); expect(html).not.toContain('Provisional grade'); expect(html).not.toContain('Presentation &amp; Handwriting is awaiting teacher review.');});
  test('omits empty optional sections and never emits Detected Issues',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).not.toContain('Detected Issues'); expect(html).not.toContain('No data available'); expect(html).not.toContain('AI Per-Category Feedback'); expect(html).not.toContain('Teacher comments</h3>');});
  test('renders a symbol-only second-file bubble while retaining the numbered correction note',()=>{const data=fixture(); data.submission.imageDataByFileId.b='data:image/png;base64,AA=='; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect(html).toContain('Submitted Page 2'); expect(html).toContain('#02 &middot; AGR'); expect(html).toMatch(/Submitted Page 2[\s\S]*marker[\s\S]*>AGR<\/b>/);});
  test('places the existing results summary after identity and before the submitted document without a forced break',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); const identity=html.indexOf('class="identity"'); const results=html.indexOf('class="results-summary"'); const scores=html.indexOf('Scores and Correction Statistics'); const submitted=html.indexOf('SUBMITTED DOCUMENT'); expect(identity).toBeLessThan(results); expect(results).toBeLessThan(scores); expect(scores).toBeLessThan(submitted); const resultTag=html.slice(results-20,results+80); expect(resultTag).not.toContain('page-break'); expect(html).toContain('.results-summary{margin-top:4mm;break-before:auto;page-break-before:auto}');});
  test('uses ordered page reviews with compact correction rows and active legend only',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); const p1=html.indexOf('Submitted Page 1'); const p2=html.indexOf('Submitted Page 2'); const feedback=html.indexOf('Detailed Feedback'); expect(p1).toBeGreaterThan(-1); expect(p1).toBeLessThan(p2); expect(p2).toBeLessThan(feedback); expect(html).toContain('class="annotated-image-page"'); expect(html).toContain('class="page-review-details"'); expect(html).toContain('class="correction-table"'); expect(html).toContain('Submitted Page 1 - correction notes'); expect(html).toContain('class="correction-line"'); expect(html).toContain('class="correction-explanation"'); expect(html).toContain('break-inside:avoid;page-break-inside:avoid'); expect(html).not.toContain('<th>No. + Type</th>'); expect(html).not.toContain('class="callout"'); expect(html).not.toContain('Complete correction legend');});
  test('image bubbles use only the official symbol while correction rows retain numbered references',()=>{const data=fixture(); data.submission.imageDataByFileId.b='data:image/png;base64,AA=='; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect((html.match(/class="marker"/g)||[])).toHaveLength(2); expect((html.match(/class="marker"[^>]*>AGR<\/b>/g)||[])).toHaveLength(2); expect(html).not.toMatch(/class="marker"[^>]*>#[0-9]/); expect(html).toContain('#01 &middot; AGR'); expect(html).toContain('#02 &middot; AGR');});
  test('normalizes canonical corner boxes and preserves canonical marker identity and color',()=>{const data=fixture(); data.submission.writingCorrections[0].bboxList=[{x0:10,y0:20,x1:25,y1:24}]; data.submission.writingCorrections[0].color='#123456'; const correction=buildSubmissionFeedbackReportViewModel(data).submittedPages[0].corrections[0]; expect(correction).toMatchObject({id:'c1',displayNumber:1,symbol:'AGR',color:'#123456',fileId:'a',page:1,bboxList:[{x:10,y:20,w:15,h:4}]});});
  test('does not broadcast missing-fileId corrections across multiple images',()=>{const data=fixture(); data.submission.writingCorrections[0].fileId=null; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages.flatMap(page=>page.corrections).map(item=>item.id)).toEqual(['c2']);});
  test('allows missing-fileId fallback only for an unambiguous single-image legacy record',()=>{const data=fixture(); data.submission.files=['a']; data.submission.transcriptPages=[data.submission.transcriptPages[1]]; data.submission.writingCorrections=[{...data.submission.writingCorrections[0],fileId:null}]; const vm=buildSubmissionFeedbackReportViewModel(data); expect(vm.submittedPages[0].corrections.map(item=>item.id)).toEqual(['c1']);});
  test('missing second image preserves its transcript and corrections',()=>{const vm=buildSubmissionFeedbackReportViewModel(fixture()); expect(vm.submittedPages[1].imageDataUrl).toBeNull(); const html=renderSubmissionFeedbackReportHtml(vm); expect(html).toContain('Submitted image unavailable'); expect(html).toMatch(/Page\s+<mark[^>]*>two/);});
  test('escapes all dynamic report text',()=>{const data=fixture(); data.identity={title:'<style>bad</style>',studentName:'<img src=x onerror=alert(1)>'}; const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(data)); expect(html).not.toContain('<style>bad</style>'); expect(html).not.toContain('<img src=x'); expect(esc('<script>')).toBe('&lt;script&gt;');});
  test('production report code has no provider calls, database writes, or page-only filtering',()=>{const fs=require('fs'); const files=['../src/services/submissionFeedbackReport.service.js','../src/modules/submissionFeedbackPdfGenerator.js','../src/pdf/submissionFeedbackReportTemplate.js'].map(p=>fs.readFileSync(require('path').join(__dirname,p),'utf8')).join('\n'); expect(files).not.toMatch(/LanguageTool|Google Vision|semantic AI|updateOne|findOneAndUpdate|\.save\(/i); expect(files).not.toMatch(/filter\s*\(.*Number\(c\.page\).*pageNum/);});
  test('annotated image page has exactly one forced page break after it',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.annotated-image-page{break-after:page;page-break-after:always}');});
  test('page review details does not force a page break before itself',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.page-review-details{break-before:auto;page-break-before:auto}'); expect(html).not.toContain('.page-review-details{break-before:page'); expect(html).not.toContain('.page-review-details{page-break-before:always');});
  test('feedback section does not use named page or force new page',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.feedback-section{page:auto;break-before:auto;page-break-before:auto'); expect(html).not.toContain('.feedback-section{page:feedback'); expect(html).not.toContain('.feedback-section{page:evidence'); expect(html).not.toMatch(/\.feedback-section[^}]*break-before:\s*page/);});
  test('correction notes do not use multi-column layout',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).not.toContain('column-count:2'); expect(html).not.toContain('.correction-flow');});
  test('correction table can fragment across pages with repeatable header',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.correction-table{break-inside:auto;page-break-inside:auto}'); expect(html).toContain('.correction-table tbody{break-inside:auto;page-break-inside:auto}'); expect(html).toContain('.correction-table thead{display:table-header-group}'); expect(html).toContain('.correction-table tr{break-inside:avoid;page-break-inside:avoid}');});
  test('new annotated image section starts on new page after page review details',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.page-review-details+.annotated-image-page{break-before:page;page-break-before:always}');});
  test('feedback section has reduced margin to save vertical space',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.feedback-section{break-before:auto;margin-top:3mm}'); expect(html).toContain('.feedback-section{page:auto;break-before:auto;page-break-before:auto;margin-top:3mm}');});
  test('correction table has reduced padding to save vertical space',()=>{const html=renderSubmissionFeedbackReportHtml(buildSubmissionFeedbackReportViewModel(fixture())); expect(html).toContain('.correction-table td{padding:.7mm 1.4mm}'); expect(html).toContain('.correction-explanation{margin-top:.3mm;line-height:1.14');});
});
