'use strict';
const express = require('express'); const request = require('supertest'); const mongoose = require('mongoose');
const { connectInMemoryMongo, disconnectInMemoryMongo, clearDatabase } = require('./helpers/testServer');
const User = require('../src/models/user.model'); const Plan = require('../src/models/Plan'); const Class = require('../src/models/class.model');
const Assignment = require('../src/models/assignment.model'); const Submission = require('../src/models/Submission'); const Feedback = require('../src/models/SubmissionFeedback');
const Session = require('../src/models/AdaptivePracticeSession'); const Attempt = require('../src/models/AdaptivePracticeAttempt');
const aiGeneration = require('../src/services/aiGeneration.service'); const adaptive = require('../src/services/adaptivePractice.service'); const service = require('../src/services/teacherAdaptivePractice.service');
const routes = require('../src/routes/adaptivePractice.routes'); const { signJwt } = require('../src/utils/jwt');

let app;
async function seed() {
  const teacher = await User.create({ firebaseUid: `teacher-${new mongoose.Types.ObjectId()}`, email: 'teacher@test.invalid', role: 'teacher' });
  const otherTeacher = await User.create({ firebaseUid: `other-${new mongoose.Types.ObjectId()}`, email: 'other@test.invalid', role: 'teacher' });
  const student = await User.create({ firebaseUid: `student-${new mongoose.Types.ObjectId()}`, email: 'student@test.invalid', role: 'student' });
  const cls = await Class.create({ name: 'Test class', teacher: teacher._id, joinCode: new mongoose.Types.ObjectId().toString().slice(-8) });
  const assignment = await Assignment.create({ title: 'Essay', deadline: new Date(Date.now() + 10000), class: cls._id, teacher: teacher._id });
  const submission = await Submission.create({ student: student._id, assignment: assignment._id, class: cls._id, status: 'submitted', submittedAt: new Date(), transcriptText: 'This is a synthetic student paragraph for practice.' });
  const feedback = await Feedback.create({ submissionId: submission._id, classId: cls._id, studentId: student._id, teacherId: teacher._id, assessmentVersion: 'v1', rubricScores: { CONTENT: { score: 10, maxScore: 20 }, ORGANIZATION: { score: 11, maxScore: 20 }, VOCABULARY: { score: 15, maxScore: 20 }, GRAMMAR: { score: 19, maxScore: 25 }, MECHANICS: { score: 8, maxScore: 10 } } });
  return { teacher, otherTeacher, student, cls, assignment, submission, feedback };
}
async function createSession(data, fingerprint, createdAt = new Date()) {
  return Session.create({ submissionId: data.submission._id, studentId: data.student._id, assignmentId: data.assignment._id, status: 'ready', sourceFingerprint: fingerprint,
    sourceSnapshot: { transcriptFingerprint: `t-${fingerprint}`, feedbackId: data.feedback._id, feedbackUpdatedAt: data.feedback.updatedAt, skills: [{ id: 'CONTENT', category: 'Task Achievement', earnedPoints: 10, maximumPoints: 20, percentage: 50, status: 'needs-practice' }, { id: 'ORGANIZATION', category: 'Coherence & Flow', earnedPoints: 11, maximumPoints: 20, percentage: 55, status: 'needs-practice' }] },
    targetSkills: ['CONTENT', 'ORGANIZATION'], activities: [{ activityId: `content-${fingerprint}`, skillId: 'CONTENT', category: 'Task Achievement', title: 'Content', description: 'd', evidence: 'This is a synthetic student paragraph for practice.', task: 't', tip: 't', checklist: ['One', 'Two'], modelAnswer: 'm', difficulty: 'developing' }, { activityId: `org-${fingerprint}`, skillId: 'ORGANIZATION', category: 'Coherence & Flow', title: 'Flow', description: 'd', evidence: 'This is a synthetic student paragraph for practice.', task: 't', tip: 't', checklist: ['One', 'Two'], modelAnswer: 'm', difficulty: 'developing' }], createdAt });
}
async function createAttempt(session, data, activityId, number, status, score, date) {
  return Attempt.create({ sessionId: session._id, submissionId: data.submission._id, studentId: data.student._id, activityId, attemptNumber: number, status, response: `Synthetic response ${number}`, responseFingerprint: `${session._id}-${activityId}-${number}`, result: status === 'ready' ? { score, passed: score >= 70, summary: 'Summary', strength: 'Strength', nextImprovement: 'Next', checklist: [{ item: 'One', met: true, feedback: 'Met' }], suggestedRevision: 'Revision', scoring: { taskFulfillment: 20, targetSkillApplication: Math.min(50, Math.max(0, score - 40)), checklistCompletion: 20 } } : undefined, createdAt: date });
}

describe('teacher adaptive practice monitoring', () => {
  beforeAll(async () => { await connectInMemoryMongo(); process.env.JWT_SECRET = 'teacher-adaptive-test-secret'; app = express(); app.use(express.json()); app.use('/api/adaptive-practice', routes); });
  afterAll(disconnectInMemoryMongo); beforeEach(async () => { await clearDatabase(); jest.restoreAllMocks(); await Plan.create({ name: 'Free', price: 0, durationDays: 30, billingType: 'monthly', limits: { classes: 10, assignments: 10, students: 10, submissions: 10, storageMB: 10 } }); });

  it('authorizes only the assignment/class teacher', async () => { const d = await seed(); expect((await service.getProgress(d.submission._id, d.teacher._id)).state).toBe('not-started'); await expect(service.getProgress(d.submission._id, d.otherTeacher._id)).rejects.toMatchObject({ status: 403 }); });
  it('returns 200 not-started when no session exists', async () => { const d = await seed(); const r = await request(app).get(`/api/adaptive-practice/teacher/submissions/${d.submission._id}/progress`).set('Authorization', `Bearer ${signJwt(d.teacher)}`); expect(r.status).toBe(200); expect(r.body.data).toMatchObject({ state: 'not-started', skills: [], summary: { totalActivities: 0, totalAttempts: 0 } }); });
  it('enforces unauthenticated, student-role, invalid-id, missing, and unrelated-teacher responses', async () => { const d = await seed(); const url = `/api/adaptive-practice/teacher/submissions/${d.submission._id}/progress`; expect((await request(app).get(url)).status).toBe(401); expect((await request(app).get(url).set('Authorization', `Bearer ${signJwt(d.student)}`)).status).toBe(403); expect((await request(app).get('/api/adaptive-practice/teacher/submissions/bad/progress').set('Authorization', `Bearer ${signJwt(d.teacher)}`)).status).toBe(400); expect((await request(app).get(`/api/adaptive-practice/teacher/submissions/${new mongoose.Types.ObjectId()}/progress`).set('Authorization', `Bearer ${signJwt(d.teacher)}`)).status).toBe(404); expect((await request(app).get(url).set('Authorization', `Bearer ${signJwt(d.otherTeacher)}`)).status).toBe(403); });
  it('selects the newest current session and never merges historical attempts', async () => { const d = await seed(); const current = (await adaptive.loadOwnedSource(d.submission._id, d.student._id)).sourceFingerprint; const old = await createSession(d, 'old', new Date('2025-01-01')); const now = await createSession(d, current, new Date('2025-02-01')); await createAttempt(old, d, old.activities[0].activityId, 1, 'ready', 99, new Date('2025-01-02')); await createAttempt(now, d, now.activities[0].activityId, 1, 'ready', 65, new Date('2025-02-02')); const result = await service.getProgress(d.submission._id, d.teacher._id); expect(result.sessionId).toBe(String(now._id)); expect(result.sourceStatus).toBe('current'); expect(result.summary.totalAttempts).toBe(1); expect(result.skills[0].bestScore).toBe(65); });
  it('returns latest historical session as outdated when no fingerprint matches', async () => { const d = await seed(); await createSession(d, 'older', new Date('2025-01-01')); const latest = await createSession(d, 'latest', new Date('2025-02-01')); const result = await service.getProgress(d.submission._id, d.teacher._id); expect(result.sessionId).toBe(String(latest._id)); expect(result.sourceStatus).toBe('outdated'); });
  it('uses best and newest ready attempts while counting failed/checking attempts only in attempt counts', async () => { const d = await seed(); const current = (await adaptive.loadOwnedSource(d.submission._id, d.student._id)).sourceFingerprint; const session = await createSession(d, current); const id = session.activities[0].activityId; await createAttempt(session, d, id, 1, 'ready', 70, new Date('2025-01-01')); await createAttempt(session, d, id, 2, 'failed', null, new Date('2025-01-02')); await createAttempt(session, d, id, 3, 'ready', 68, new Date('2025-01-03')); await createAttempt(session, d, id, 4, 'checking', null, new Date('2025-01-04')); const result = await service.getProgress(d.submission._id, d.teacher._id); expect(result.skills[0]).toMatchObject({ attemptCount: 4, latestScore: 68, bestScore: 70, improved: true }); expect(result.summary.totalAttempts).toBe(4); });
  it('paginates newest-first, caps page size, and excludes sensitive fields', async () => { const d = await seed(); const session = await createSession(d, 'history'); const id = session.activities[0].activityId; for (let i = 1; i <= 3; i++) await createAttempt(session, d, id, i, 'ready', 60 + i, new Date(2025, 0, i)); const result = await service.getAttempts(session._id, id, d.teacher._id, 1, 100); expect(result.pagination).toMatchObject({ limit: 25, total: 3 }); expect(result.attempts.map((a) => a.attemptNumber)).toEqual([3, 2, 1]); const serialized = JSON.stringify(result); expect(serialized).not.toMatch(/modelAnswer|sourceFingerprint|responseFingerprint|provider|promptVersion|checking/); });
  it('enforces history ownership and activity membership', async () => { const d = await seed(); const session = await createSession(d, 'history'); await expect(service.getAttempts(session._id, session.activities[0].activityId, d.otherTeacher._id, 1, 10)).rejects.toMatchObject({ status: 403 }); await expect(service.getAttempts(session._id, 'not-an-activity', d.teacher._id, 1, 10)).rejects.toMatchObject({ status: 404 }); });
  it('performs reads only and never calls AI', async () => { const d = await seed(); const current = (await adaptive.loadOwnedSource(d.submission._id, d.student._id)).sourceFingerprint; const session = await createSession(d, current); await createAttempt(session, d, session.activities[0].activityId, 1, 'ready', 75, new Date()); const before = JSON.stringify({ submission: await Submission.findById(d.submission._id).lean(), feedback: await Feedback.findById(d.feedback._id).lean(), session: await Session.findById(session._id).lean(), attempts: await Attempt.find({ sessionId: session._id }).lean() }); const spy = jest.spyOn(aiGeneration, 'generateChatCompletion'); await service.getProgress(d.submission._id, d.teacher._id); await service.getAttempts(session._id, session.activities[0].activityId, d.teacher._id, 1, 10); const after = JSON.stringify({ submission: await Submission.findById(d.submission._id).lean(), feedback: await Feedback.findById(d.feedback._id).lean(), session: await Session.findById(session._id).lean(), attempts: await Attempt.find({ sessionId: session._id }).lean() }); expect(after).toBe(before); expect(spy).not.toHaveBeenCalled(); });
});
