'use strict';
const path = require('path');
const { buildSubmissionFeedbackReportViewModel } = require('../src/pdf/sample/submissionFeedbackReportViewModel');
const { getOfficialCorrectionLegend } = require('../src/services/correctionLegendCatalog.service');
const { generateSubmissionFeedbackPdf } = require('../src/modules/submissionFeedbackPdfGenerator');

const ROOT = path.resolve(__dirname, '..', '..');
const outputPath = path.join(ROOT, 'output', 'pdf', 'RoznaHub-Production-Submission-Feedback-Report.pdf');
const debugHtmlPath = path.join(ROOT, 'tmp', 'pdfs', 'production-submission-feedback-report.html');
const colors = { CONTENT:'#e89b3c', ORGANIZATION:'#3b82a0', GRAMMAR:'#39956b', VOCABULARY:'#8958b8', MECHANICS:'#c59a15' };
const page1 = 'Artificial intelligence are changing education in many ways. Students learns at different speeds, and smart tools provides personalized practice. AI tutors is available at any time, but every student have different needs.';
const page2 = 'Automated grading reduce repetitive work and allow educators to focuses on student progress. However this informations must be protected carefully. In conclusion, AI provide valuable support responsibly.';
const canonicalText = `${page1}\n\n${page2}`; const page2Start = page1.length + 2;
const svg = (title, lines) => `data:image/svg+xml;base64,${Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="1180"><rect width="900" height="1180" fill="#fffdf7"/><rect x="25" y="25" width="850" height="1130" rx="10" fill="none" stroke="#d7d0bf" stroke-width="2"/><text x="58" y="62" font-family="Arial" font-size="18" fill="#718096">${title}</text>${lines.map((line,index)=>`<text x="58" y="${105+index*42}" font-family="Arial" font-size="22" fill="#24364a">${line}</text>`).join('')}</svg>`).toString('base64')}`;
const make = (id,fileId,category,symbol,quote,message,suggestedText,bboxList) => { const startChar=canonicalText.indexOf(quote); return { id,fileId,page:1,category,symbol,color:colors[category],quotedText:quote,message,suggestedText,startChar,endChar:startChar+quote.length,bboxList }; };
const corrections = [
  make('c1','file-1','GRAMMAR','AGR','intelligence are','Use singular agreement.','intelligence is',[{x:25,y:6.5,w:18,h:2.2}]),
  make('c2','file-1','GRAMMAR','AGR','Students learns','Plural subjects require the base verb.','Students learn',[{x:6.5,y:10.1,w:16,h:2.2},{x:23,y:10.1,w:10,h:2.2}]),
  make('c3','file-1','GRAMMAR','AGR','tools provides','Use the base verb with a plural subject.','tools provide',[{x:50,y:10.1,w:17,h:2.2}]),
  make('c4','file-1','CONTENT','SD','different needs','Add a concrete learner example.','different needs, such as pacing support',[{x:39,y:17.2,w:17,h:2.2}]),
  make('c5','file-1','MECHANICS','P','time, but','Strengthen the clause boundary.','time; however,',[{x:7,y:17.2,w:13,h:2.2}]),
  make('c6','file-2','GRAMMAR','AGR','grading reduce','The singular subject requires reduces.','grading reduces',[{x:18,y:6.5,w:16,h:2.2}]),
  make('c7','file-2','GRAMMAR','VF','to focuses','Use the base form after to.','to focus',[{x:6.5,y:10.1,w:12,h:2.2}]),
  make('c8','file-2','MECHANICS','P','However this','Add a comma after the introductory word.','However, this',[{x:6.5,y:13.7,w:14,h:2.2}]),
  make('c9','file-2','VOCABULARY','WF','this informations','Information is uncountable.','this information',[{x:19,y:13.7,w:19,h:2.2}]),
  make('c10','file-2','ORGANIZATION','CONC','In conclusion, AI provide valuable support responsibly.','Synthesize the main benefits and responsible-use condition.','Expand the conclusion.',[{x:6.5,y:17.2,w:27,h:2.2},{x:34,y:17.2,w:31,h:2.2}])
];
const rubricScores={CONTENT:{score:17,maxScore:20,comment:'Relevant response; one claim needs supporting detail.'},ORGANIZATION:{score:16,maxScore:20,comment:'Clear progression; conclusion needs development.'},GRAMMAR:{score:19,maxScore:25,comment:'Agreement and verb-form patterns need revision.'},VOCABULARY:{score:17,maxScore:20,comment:'Generally clear vocabulary with one word-form issue.'},MECHANICS:{score:9,maxScore:10,comment:'Mostly controlled punctuation.'},PRESENTATION:{score:5,maxScore:5,comment:'Both submitted pages are readable.'}};
const detailedFeedback={areasForImprovement:[{title:'Grammar',category:'GRAMMAR',score:19,maxScore:25,issueCount:5,explanation:'Subject-verb agreement is the most frequent pattern.',examples:[{quotedText:'Students learns',message:'Plural subjects require the base verb.',suggestedText:'Students learn'}]},{title:'Organization',category:'ORGANIZATION',score:16,maxScore:20,issueCount:1,explanation:'The conclusion should synthesize the central benefits and responsible use.'}],strengths:[{title:'Content',category:'CONTENT',score:17,maxScore:20,explanation:'The response addresses learning, grading, access, and responsible use.',evidence:['The discussion maintains a consistent educational focus across both pages.']}],actionSteps:[{priority:1,action:'Review every highlighted subject and verb.',reason:'Agreement is the dominant repeated pattern.',relatedSymbols:['AGR','VF']},{priority:2,action:'Add one concrete example to the learner-needs claim.',reason:'The supporting-detail marker identifies an unsupported generalization.',relatedSymbols:['SD']},{priority:3,action:'Expand the conclusion.',reason:'The current ending does not synthesize the main argument.',relatedSymbols:['CONC']} ]};
const vm=buildSubmissionFeedbackReportViewModel({generatedAt:'2026-07-19T09:30:00Z',identity:{title:'The Role of AI in Modern Education',studentName:'Amina Rahman',studentEmail:'amina@example.edu',teacherName:'Ms. Nadia Karim',className:'Academic Writing - Level 2',submittedAt:'18 July 2026'},legend:getOfficialCorrectionLegend(),submission:{_id:'sample',files:['file-1','file-2'],canonicalText,correctionStatus:'completed',correctionSourceHash:'sample-hash',writingCorrections:corrections,correctionStatistics:{content:1,grammar:5,organization:1,vocabulary:1,mechanics:2,total:10},transcriptPages:[{fileId:'file-1',pageNumber:1,startChar:0,endChar:page1.length,text:page1,imageWidth:900,imageHeight:1180},{fileId:'file-2',pageNumber:1,startChar:page2Start,endChar:canonicalText.length,text:page2,imageWidth:900,imageHeight:1180}],imageDataByPageKey:{'file-1:1':svg('Submitted page 1',['Artificial intelligence are changing education in many ways.','Students learns at different speeds, and smart tools provides','personalized practice. AI tutors is available at any time,','but every student have different needs.']),'file-2:1':svg('Submitted page 2',['Automated grading reduce repetitive work and allow educators','to focuses on student progress. However this informations','must be protected carefully.','In conclusion, AI provide valuable support responsibly.'])}},evaluation:{evaluationSourceHash:'sample-hash',status:'completed',grade:'B',rubricScores},feedback:{detailedFeedbackSourceHash:'sample-hash',detailedFeedback,teacherComments:'Strong topic selection. Revise the repeated agreement patterns before the final draft.'}});
module.exports={vm,outputPath,debugHtmlPath};
if(require.main===module){const manager=require('../src/services/pdfBrowserManager.service'); generateSubmissionFeedbackPdf(vm,outputPath,{debugHtmlPath}).then(()=>console.log(JSON.stringify({outputPath,debugHtmlPath,pages:vm.submittedPages.length,corrections:corrections.length}))).catch((error)=>{console.error(error);process.exitCode=1;}).finally(()=>manager.closeBrowser());}
