'use strict';
const crypto = require('crypto'); const mongoose = require('mongoose');
const connectDB = require('../src/config/db'); const { signJwt } = require('../src/utils/jwt');
const User = require('../src/models/user.model'); const Class = require('../src/models/class.model'); const Assignment = require('../src/models/assignment.model');
const Submission = require('../src/models/Submission'); const Feedback = require('../src/models/SubmissionFeedback'); const Session = require('../src/models/AdaptivePracticeSession'); const Attempt = require('../src/models/AdaptivePracticeAttempt');
const adaptive = require('../src/services/adaptivePractice.service');
const marker = `adaptive-phase4-${Date.now()}`; const hash = (v) => crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
async function api(path, user, query = '') { const response = await fetch(`http://localhost:5000${path}${query}`, { headers: user ? { Authorization: `Bearer ${signJwt(user)}` } : {} }); return { status: response.status, body: await response.json() }; }
async function main() {
  await connectDB();
  const teacher = await User.create({ firebaseUid: `${marker}-teacher`, email: `${marker}-teacher@example.invalid`, displayName: `${marker}-teacher`, role: 'teacher' });
  const otherTeacher = await User.create({ firebaseUid: `${marker}-other-teacher`, email: `${marker}-other-teacher@example.invalid`, displayName: `${marker}-other-teacher`, role: 'teacher' });
  const student = await User.create({ firebaseUid: `${marker}-student`, email: `${marker}-student@example.invalid`, displayName: `${marker}-student`, role: 'student' });
  const cls = await Class.create({ name: marker, teacher: teacher._id, joinCode: `P4${Date.now().toString(36).slice(-8)}`.toUpperCase() });
  const assignment = await Assignment.create({ title: `${marker} assignment`, deadline: new Date(Date.now() + 86400000), class: cls._id, teacher: teacher._id });
  const noSessionAssignment = await Assignment.create({ title: `${marker} no-session assignment`, deadline: new Date(Date.now() + 86400000), class: cls._id, teacher: teacher._id });
  const submission = await Submission.create({ student: student._id, assignment: assignment._id, class: cls._id, status: 'submitted', submittedAt: new Date(), transcriptText: 'Synthetic monitoring text connects ideas and uses precise vocabulary.' });
  const noSessionSubmission = await Submission.create({ student: student._id, assignment: noSessionAssignment._id, class: cls._id, status: 'submitted', submittedAt: new Date(), transcriptText: 'Synthetic no-session monitoring text.' });
  const feedback = await Feedback.create({ submissionId: submission._id, classId: cls._id, studentId: student._id, teacherId: teacher._id, assessmentVersion: 'synthetic-phase4-v1', overallScore: 66, rubricScores: { CONTENT: { score: 10, maxScore: 20 }, ORGANIZATION: { score: 11, maxScore: 20 }, VOCABULARY: { score: 15, maxScore: 20 }, GRAMMAR: { score: 19, maxScore: 25 }, MECHANICS: { score: 8, maxScore: 10 } } });
  const source = await adaptive.loadOwnedSource(submission._id, student._id);
  const activities = [{ activityId: 'phase4-content', skillId: 'CONTENT', category: 'Task Achievement', title: 'Content', description: 'Synthetic.', evidence: 'Synthetic monitoring text connects ideas and uses precise vocabulary.', task: 'Revise.', tip: 'Focus.', checklist: ['Addresses the task', 'Adds support'], modelAnswer: 'Private model answer', difficulty: 'developing' }, { activityId: 'phase4-organization', skillId: 'ORGANIZATION', category: 'Coherence & Flow', title: 'Flow', description: 'Synthetic.', evidence: 'Synthetic monitoring text connects ideas and uses precise vocabulary.', task: 'Connect.', tip: 'Transition.', checklist: ['Uses transitions', 'Logical order'], modelAnswer: 'Private model answer', difficulty: 'developing' }];
  const session = await Session.create({ submissionId: submission._id, studentId: student._id, assignmentId: assignment._id, status: 'ready', sourceFingerprint: source.sourceFingerprint, sourceSnapshot: { transcriptFingerprint: source.transcriptFingerprint, feedbackId: feedback._id, feedbackUpdatedAt: feedback.updatedAt, skills: source.assessedSkills }, targetSkills: ['CONTENT', 'ORGANIZATION'], activities, generation: { provider: 'openrouter', model: 'openai/gpt-oss-120b', promptVersion: 'private-generation-prompt' } });
  const attemptData = [[1, 'ready', 75], [2, 'failed', null], [3, 'ready', 72], [4, 'checking', null]];
  const attempts = [];
  for (const [attemptNumber, status, score] of attemptData) attempts.push(await Attempt.create({ sessionId: session._id, submissionId: submission._id, studentId: student._id, activityId: 'phase4-content', attemptNumber, status, response: `Synthetic teacher-monitoring response ${attemptNumber}.`, responseFingerprint: `${marker}-${attemptNumber}`, result: status === 'ready' ? { score, passed: score >= 70, summary: 'Synthetic summary', strength: 'Synthetic strength', nextImprovement: 'Synthetic next step', checklist: [{ item: 'Addresses the task', met: true, feedback: 'Met' }], suggestedRevision: 'Synthetic suggested revision', scoring: { taskFulfillment: 20, targetSkillApplication: 35, checklistCompletion: score - 55 } } : undefined, checking: { provider: 'openrouter', model: 'private-model', promptVersion: 'private-check-prompt', errorMessage: status === 'failed' ? 'private provider error' : undefined } }));
  const snapshot = async () => ({ submission: await Submission.findById(submission._id).lean(), noSessionSubmission: await Submission.findById(noSessionSubmission._id).lean(), feedback: await Feedback.findById(feedback._id).lean(), session: await Session.findById(session._id).lean(), attempts: await Attempt.find({ sessionId: session._id }).sort({ attemptNumber: 1 }).lean() });
  const before = hash(await snapshot());
  const owner = await api(`/api/adaptive-practice/teacher/submissions/${submission._id}/progress`, teacher);
  const unrelated = await api(`/api/adaptive-practice/teacher/submissions/${submission._id}/progress`, otherTeacher);
  const studentResult = await api(`/api/adaptive-practice/teacher/submissions/${submission._id}/progress`, student);
  const noSession = await api(`/api/adaptive-practice/teacher/submissions/${noSessionSubmission._id}/progress`, teacher);
  const history = await api(`/api/adaptive-practice/teacher/sessions/${session._id}/activities/phase4-content/attempts`, teacher, '?page=1&limit=2');
  const after = hash(await snapshot());
  const serialized = JSON.stringify({ owner: owner.body, history: history.body }); const sensitiveAbsent = !/modelAnswer|sourceFingerprint|responseFingerprint|provider|promptVersion|errorMessage|generation/.test(serialized);
  process.stdout.write(JSON.stringify({ marker, ids: { teacher: teacher._id, otherTeacher: otherTeacher._id, student: student._id, class: cls._id, assignment: assignment._id, noSessionAssignment: noSessionAssignment._id, submission: submission._id, noSessionSubmission: noSessionSubmission._id, feedback: feedback._id, session: session._id, attempts: attempts.map((a) => a._id) }, results: { ownerStatus: owner.status, ownerData: owner.body.data, unrelatedStatus: unrelated.status, studentStatus: studentResult.status, noSessionStatus: noSession.status, noSessionState: noSession.body.data?.state, historyStatus: history.status, historyPagination: history.body.data?.pagination, sensitiveAbsent, sourceHashUnchanged: before === after, aiCallsMadeByReadEndpoints: 0 } }, null, 2));
}
main().catch((e) => { process.stderr.write(`${e.message}\n`); process.exitCode = 1; }).finally(() => mongoose.disconnect());
