const mongoose = require('mongoose');

const { Schema } = mongoose;

// Factory to create rubric item schemas with category-specific maximum scores
const createRubricItemSchema = (maxScore) =>
  new Schema(
    {
      score: {
        type: Number,
        default: 0,
        min: 0,
        max: maxScore
      },
      maxScore: {
        type: Number,
        default: maxScore,
        required: true
      },
      comment: {
        type: String,
        default: '',
        trim: true
      }
      ,issueCount: { type: Number, default: 0, min: 0 }
    },
    { _id: false }
  );

const rubricItemSchema = new Schema(
  {
    score: { type: Number, default: 0 },
    maxScore: { type: Number, default: 5 },
    comment: { type: String, default: '', trim: true }
  },
  {
    _id: false
  }
);

const correctionStatsSchema = new Schema(
  {
    content: { type: Number, default: 0 },
    grammar: { type: Number, default: 0 },
    organization: { type: Number, default: 0 },
    vocabulary: { type: Number, default: 0 },
    mechanics: { type: Number, default: 0 },
    total: { type: Number, default: 0 }
  },
  { _id: false }
);

const detailedFeedbackSchema = new Schema(
  {
    strengths: { type: [String], default: [] },
    areasForImprovement: { type: [String], default: [] },
    actionSteps: { type: [String], default: [] }
  },
  { _id: false }
);

const aiFeedbackPerCategorySchema = new Schema(
  {
    category: { type: String, default: '', trim: true },
    message: { type: String, default: '', trim: true },
    score: { type: Number, default: 0 },
    maxScore: { type: Number, default: 5 },
    scoreOutOf5: { type: Number, default: 0 }
  },
  { _id: false }
);

const aiFeedbackSchema = new Schema(
  {
    perCategory: { type: [aiFeedbackPerCategorySchema], default: [] },
    overallComments: { type: String, default: '', trim: true }
  },
  { _id: false }
);

 const rubricDesignerLevelSchema = new Schema(
   {
     title: { type: String, default: '', trim: true },
     maxPoints: { type: Number, default: 0 }
   },
   { _id: false }
 );

 const rubricDesignerCriteriaSchema = new Schema(
   {
     title: { type: String, default: '', trim: true },
     cells: { type: [String], default: [] }
   },
   { _id: false }
 );

 const rubricDesignerSchema = new Schema(
   {
     title: { type: String, default: '', trim: true },
     levels: { type: [rubricDesignerLevelSchema], default: [] },
     criteria: { type: [rubricDesignerCriteriaSchema], default: [] }
   },
   { _id: false }
 );

const submissionFeedbackSchema = new Schema(
  {
    submissionId: { type: Schema.Types.ObjectId, ref: 'Submission', required: true, unique: true, index: true },
    classId: { type: Schema.Types.ObjectId, ref: 'Class', required: true, index: true },
    studentId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    teacherId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },

    // Assessment version to track rubric changes (e.g., "writing-rubric-100-v1")
    assessmentVersion: { type: String, default: 'writing-rubric-100-v1', trim: true },

    // Maximum overall score (e.g., 100 for new rubric)
    maxOverallScore: { type: Number, default: 100, min: 0 },

    rubricScores: {
      CONTENT: { type: createRubricItemSchema(20), default: () => ({}) },
      ORGANIZATION: { type: createRubricItemSchema(20), default: () => ({}) },
      GRAMMAR: { type: createRubricItemSchema(25), default: () => ({}) },
      VOCABULARY: { type: createRubricItemSchema(20), default: () => ({}) },
      MECHANICS: { type: createRubricItemSchema(10), default: () => ({}) },
      PRESENTATION: { type: createRubricItemSchema(5), default: () => ({}) }
    },

    // Overall score is out of 100 (AI-generated by default; teacher can override).
    overallScore: { type: Number, default: 0, min: 0, max: 100 },
    evaluationSourceHash: { type: String, trim: true },
    evaluationJobId: { type: String, trim: true },
    evaluationVersion: { type: String, trim: true },
    evaluationRubricSourceHash: { type: String, trim: true },
    evaluationSource: { type: String, enum: ['ai', 'deterministic_fallback'], default: 'deterministic_fallback' },
    grade: { type: String, default: 'F', trim: true },

    // Always AI-generated from LanguageTool/annotations counts (not teacher-authored).
    correctionStats: { type: correctionStatsSchema, default: () => ({}) },

    // AI-generated defaults, teacher can override.
    detailedFeedback: { type: Schema.Types.Mixed, default: () => ({ strengths: [], areasForImprovement: [], actionSteps: [] }) },
    detailedFeedbackSourceHash: { type: String, trim: true },
    detailedFeedbackVersion: { type: String, trim: true },

    // Bottom AI feedback section (AI-generated, teacher can override).
    aiFeedback: { type: aiFeedbackSchema, default: () => ({}) },

    // Rubric modal designer (AI-generated by default; teacher can override).
    rubricDesigner: { type: rubricDesignerSchema, default: null },

    // Teacher override tracking.
    overriddenByTeacher: { type: Boolean, default: false }
  },
  {
    timestamps: true,
    collection: 'submission_feedback'
  }
);

module.exports = mongoose.model('SubmissionFeedback', submissionFeedbackSchema);
